
#
# Set some env variables
#
ARCH?=amd64
GO_VERSION?=1.9.2
K8S_VERSION?=v1.6.6

.PHONY: magnet-vars
magnet-vars:
	@echo MAGNET_ARCH=${ARCH}
	@echo MAGNET_GO_VERSION=${GO_VERSION}
	@echo MAGNET_K8S_VERSION=${K8S_VERSION}
